{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a25ddfa5-01b7-42b4-831a-cc551b406a7e",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception. in python"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7ef6fd2d-8f5d-46cc-96fa-cacf12f228d0",
   "metadata": {},
   "source": [
    "Answere :- In Python, exceptions are used to indicate that an error or unexpected event has occurred during the execution of a program. Python provides a set of built-in exceptions that can be raised by the interpreter or the programmer. However, sometimes the built-in exceptions are not sufficient to convey the specific nature of an error or problem in the program . When we encounter such a scenario where the built-in exceptions are not enough, we can create our own exceptions, which are known as custom exceptions. These custom exceptions are created by creating a new class that inherits from the Exception class. The reason for using the Exception class as the base class for custom exceptions is that it provides a standard interface for handling exceptions. By inheriting from the Exception class, our custom exception class will have access to all the methods and attributes of the Exception class, which can be used to handle the exception in a consistent and standardized way.For example, when we catch an exception, we can use the 'except' clause followed by the type of the exception, and the code in the 'except' block will only execute if the exception is of that type or a subclass of it. By inheriting from the Exception class, our custom exception class can be caught and handled in the same way as any other exception. In summary, we use the Exception class while creating a custom exception in Python because it provides a standard interface for handling exceptions and allows our custom exception class to be caught and handled in the same way as any other exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b8c773e0-908f-43e3-aadb-a0e50da6a164",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1be6339c-5e91-4948-a2f7-31c1d428f966",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'Exception'>\n",
      "  <class 'TypeError'>\n",
      "    <class 'decimal.FloatOperation'>\n",
      "    <class 'email.errors.MultipartConversionError'>\n",
      "  <class 'StopAsyncIteration'>\n",
      "  <class 'StopIteration'>\n",
      "  <class 'ImportError'>\n",
      "    <class 'ModuleNotFoundError'>\n",
      "    <class 'zipimport.ZipImportError'>\n",
      "  <class 'OSError'>\n",
      "    <class 'ConnectionError'>\n",
      "      <class 'BrokenPipeError'>\n",
      "      <class 'ConnectionAbortedError'>\n",
      "      <class 'ConnectionRefusedError'>\n",
      "      <class 'ConnectionResetError'>\n",
      "        <class 'http.client.RemoteDisconnected'>\n",
      "    <class 'BlockingIOError'>\n",
      "    <class 'ChildProcessError'>\n",
      "    <class 'FileExistsError'>\n",
      "    <class 'FileNotFoundError'>\n",
      "    <class 'IsADirectoryError'>\n",
      "    <class 'NotADirectoryError'>\n",
      "    <class 'InterruptedError'>\n",
      "      <class 'zmq.error.InterruptedSystemCall'>\n",
      "    <class 'PermissionError'>\n",
      "    <class 'ProcessLookupError'>\n",
      "    <class 'TimeoutError'>\n",
      "    <class 'io.UnsupportedOperation'>\n",
      "    <class 'signal.itimer_error'>\n",
      "    <class 'socket.herror'>\n",
      "    <class 'socket.gaierror'>\n",
      "    <class 'ssl.SSLError'>\n",
      "      <class 'ssl.SSLCertVerificationError'>\n",
      "      <class 'ssl.SSLZeroReturnError'>\n",
      "      <class 'ssl.SSLWantWriteError'>\n",
      "      <class 'ssl.SSLWantReadError'>\n",
      "      <class 'ssl.SSLSyscallError'>\n",
      "      <class 'ssl.SSLEOFError'>\n",
      "    <class 'shutil.Error'>\n",
      "      <class 'shutil.SameFileError'>\n",
      "    <class 'shutil.SpecialFileError'>\n",
      "    <class 'shutil.ExecError'>\n",
      "    <class 'shutil.ReadError'>\n",
      "    <class 'urllib.error.URLError'>\n",
      "      <class 'urllib.error.HTTPError'>\n",
      "      <class 'urllib.error.ContentTooShortError'>\n",
      "    <class 'gzip.BadGzipFile'>\n",
      "  <class 'EOFError'>\n",
      "    <class 'asyncio.exceptions.IncompleteReadError'>\n",
      "  <class 'RuntimeError'>\n",
      "    <class 'RecursionError'>\n",
      "    <class 'NotImplementedError'>\n",
      "      <class 'zmq.error.ZMQVersionError'>\n",
      "      <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "    <class '_frozen_importlib._DeadlockError'>\n",
      "    <class 'threading.BrokenBarrierError'>\n",
      "    <class 'concurrent.futures._base.BrokenExecutor'>\n",
      "      <class 'concurrent.futures.thread.BrokenThreadPool'>\n",
      "    <class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
      "    <class 'pkg_resources.ExtractionError'>\n",
      "    <class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
      "  <class 'NameError'>\n",
      "    <class 'UnboundLocalError'>\n",
      "  <class 'AttributeError'>\n",
      "    <class 'dataclasses.FrozenInstanceError'>\n",
      "  <class 'SyntaxError'>\n",
      "    <class 'IndentationError'>\n",
      "      <class 'TabError'>\n",
      "  <class 'LookupError'>\n",
      "    <class 'IndexError'>\n",
      "    <class 'KeyError'>\n",
      "      <class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
      "      <class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
      "    <class 'encodings.CodecRegistryError'>\n",
      "  <class 'ValueError'>\n",
      "    <class 'UnicodeError'>\n",
      "      <class 'UnicodeEncodeError'>\n",
      "      <class 'UnicodeDecodeError'>\n",
      "      <class 'UnicodeTranslateError'>\n",
      "    <class 'io.UnsupportedOperation'>\n",
      "    <class 'json.decoder.JSONDecodeError'>\n",
      "    <class 'ssl.SSLCertVerificationError'>\n",
      "    <class 'binascii.Error'>\n",
      "    <class '_hashlib.UnsupportedDigestmodError'>\n",
      "    <class 'calendar.IllegalMonthError'>\n",
      "    <class 'calendar.IllegalWeekdayError'>\n",
      "    <class 'dateutil.parser._parser.ParserError'>\n",
      "    <class 'pygments.util.ClassNotFound'>\n",
      "    <class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
      "    <class 'email.errors.MessageDefect'>\n",
      "      <class 'email.errors.NoBoundaryInMultipartDefect'>\n",
      "      <class 'email.errors.StartBoundaryNotFoundDefect'>\n",
      "      <class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
      "      <class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
      "      <class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
      "      <class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
      "      <class 'email.errors.MultipartInvariantViolationDefect'>\n",
      "      <class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
      "      <class 'email.errors.UndecodableBytesDefect'>\n",
      "      <class 'email.errors.InvalidBase64PaddingDefect'>\n",
      "      <class 'email.errors.InvalidBase64CharactersDefect'>\n",
      "      <class 'email.errors.InvalidBase64LengthDefect'>\n",
      "      <class 'email.errors.HeaderDefect'>\n",
      "        <class 'email.errors.InvalidHeaderDefect'>\n",
      "        <class 'email.errors.HeaderMissingRequiredValue'>\n",
      "        <class 'email.errors.NonPrintableDefect'>\n",
      "        <class 'email.errors.ObsoleteHeaderDefect'>\n",
      "        <class 'email.errors.NonASCIILocalPartDefect'>\n",
      "        <class 'email.errors.InvalidDateDefect'>\n",
      "    <class 'IPython.core.magics.code.MacroToEdit'>\n",
      "    <class 'plistlib.InvalidFileException'>\n",
      "    <class 'pkg_resources._vendor.more_itertools.more.UnequalIterablesError'>\n",
      "    <class 'pkg_resources.extern.packaging.version.InvalidVersion'>\n",
      "    <class 'pkg_resources._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader'>\n",
      "    <class 'pkg_resources.extern.packaging.utils.InvalidWheelFilename'>\n",
      "    <class 'pkg_resources.extern.packaging.utils.InvalidSdistFilename'>\n",
      "    <class 'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'>\n",
      "    <class 'pkg_resources.extern.packaging.markers.InvalidMarker'>\n",
      "    <class 'pkg_resources.extern.packaging.markers.UndefinedComparison'>\n",
      "    <class 'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'>\n",
      "    <class 'pkg_resources.extern.packaging.requirements.InvalidRequirement'>\n",
      "      <class 'pkg_resources.RequirementParseError'>\n",
      "    <class 'packaging.version.InvalidVersion'>\n",
      "  <class 'AssertionError'>\n",
      "  <class 'ArithmeticError'>\n",
      "    <class 'FloatingPointError'>\n",
      "    <class 'OverflowError'>\n",
      "    <class 'ZeroDivisionError'>\n",
      "      <class 'decimal.DivisionByZero'>\n",
      "      <class 'decimal.DivisionUndefined'>\n",
      "    <class 'decimal.DecimalException'>\n",
      "      <class 'decimal.Clamped'>\n",
      "      <class 'decimal.Rounded'>\n",
      "        <class 'decimal.Underflow'>\n",
      "        <class 'decimal.Overflow'>\n",
      "      <class 'decimal.Inexact'>\n",
      "        <class 'decimal.Underflow'>\n",
      "        <class 'decimal.Overflow'>\n",
      "      <class 'decimal.Subnormal'>\n",
      "        <class 'decimal.Underflow'>\n",
      "      <class 'decimal.DivisionByZero'>\n",
      "      <class 'decimal.FloatOperation'>\n",
      "      <class 'decimal.InvalidOperation'>\n",
      "        <class 'decimal.ConversionSyntax'>\n",
      "        <class 'decimal.DivisionImpossible'>\n",
      "        <class 'decimal.DivisionUndefined'>\n",
      "        <class 'decimal.InvalidContext'>\n",
      "  <class 'SystemError'>\n",
      "    <class 'encodings.CodecRegistryError'>\n",
      "  <class 'ReferenceError'>\n",
      "  <class 'MemoryError'>\n",
      "  <class 'BufferError'>\n",
      "  <class 'Warning'>\n",
      "    <class 'UserWarning'>\n",
      "      <class 'getpass.GetPassWarning'>\n",
      "      <class 'IPython.core.formatters.FormatterWarning'>\n",
      "    <class 'EncodingWarning'>\n",
      "    <class 'DeprecationWarning'>\n",
      "      <class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
      "    <class 'PendingDeprecationWarning'>\n",
      "    <class 'SyntaxWarning'>\n",
      "    <class 'RuntimeWarning'>\n",
      "      <class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
      "      <class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
      "      <class 'pkg_resources.PEP440Warning'>\n",
      "    <class 'FutureWarning'>\n",
      "      <class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
      "    <class 'ImportWarning'>\n",
      "    <class 'UnicodeWarning'>\n",
      "    <class 'BytesWarning'>\n",
      "    <class 'ResourceWarning'>\n",
      "    <class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
      "    <class 'pkg_resources.PkgResourcesDeprecationWarning'>\n",
      "  <class 'warnings._OptionError'>\n",
      "  <class 'runpy._Error'>\n",
      "  <class 're.error'>\n",
      "  <class 'sre_parse.Verbose'>\n",
      "  <class 'locale.Error'>\n",
      "  <class 'subprocess.SubprocessError'>\n",
      "    <class 'subprocess.CalledProcessError'>\n",
      "    <class 'subprocess.TimeoutExpired'>\n",
      "  <class 'tokenize.TokenError'>\n",
      "  <class 'tokenize.StopTokenizing'>\n",
      "  <class 'inspect.ClassFoundException'>\n",
      "  <class 'inspect.EndOfBlock'>\n",
      "  <class 'traitlets.traitlets.TraitError'>\n",
      "  <class 'copy.Error'>\n",
      "  <class 'concurrent.futures._base.Error'>\n",
      "    <class 'concurrent.futures._base.CancelledError'>\n",
      "    <class 'concurrent.futures._base.TimeoutError'>\n",
      "    <class 'concurrent.futures._base.InvalidStateError'>\n",
      "  <class 'socket._GiveupOnSendfile'>\n",
      "  <class 'struct.error'>\n",
      "  <class 'binascii.Incomplete'>\n",
      "  <class 'asyncio.exceptions.TimeoutError'>\n",
      "  <class 'asyncio.exceptions.InvalidStateError'>\n",
      "  <class 'asyncio.exceptions.LimitOverrunError'>\n",
      "  <class 'asyncio.queues.QueueEmpty'>\n",
      "  <class 'asyncio.queues.QueueFull'>\n",
      "  <class '_queue.Empty'>\n",
      "  <class 'queue.Full'>\n",
      "  <class 'ctypes.ArgumentError'>\n",
      "  <class 'zmq.error.ZMQBaseError'>\n",
      "    <class 'zmq.error.ZMQError'>\n",
      "      <class 'zmq.error.ContextTerminated'>\n",
      "      <class 'zmq.error.Again'>\n",
      "      <class 'zmq.error.InterruptedSystemCall'>\n",
      "    <class 'zmq.error.ZMQBindError'>\n",
      "    <class 'zmq.error.NotDone'>\n",
      "  <class '_pickle.PickleError'>\n",
      "    <class '_pickle.PicklingError'>\n",
      "    <class '_pickle.UnpicklingError'>\n",
      "  <class 'pickle._Stop'>\n",
      "  <class 'argparse.ArgumentError'>\n",
      "  <class 'argparse.ArgumentTypeError'>\n",
      "  <class 'traitlets.config.loader.ConfigError'>\n",
      "    <class 'traitlets.config.loader.ConfigLoaderError'>\n",
      "      <class 'traitlets.config.loader.ArgumentError'>\n",
      "    <class 'traitlets.config.loader.ConfigFileNotFound'>\n",
      "  <class 'traitlets.config.configurable.ConfigurableError'>\n",
      "    <class 'traitlets.config.configurable.MultipleInstanceError'>\n",
      "  <class 'traitlets.config.application.ApplicationError'>\n",
      "  <class 'zlib.error'>\n",
      "  <class 'tornado.util.TimeoutError'>\n",
      "  <class '_curses.error'>\n",
      "  <class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
      "  <class 'tornado.gen.KeyReuseError'>\n",
      "  <class 'tornado.gen.UnknownKeyError'>\n",
      "  <class 'tornado.gen.LeakedCallbackError'>\n",
      "  <class 'tornado.gen.BadYieldError'>\n",
      "  <class 'tornado.gen.ReturnValueIgnoredError'>\n",
      "  <class 'tornado.gen.Return'>\n",
      "  <class 'jupyter_client.channels.InvalidPortNumber'>\n",
      "  <class 'termios.error'>\n",
      "  <class '_lzma.LZMAError'>\n",
      "  <class 'shutil.RegistryError'>\n",
      "  <class 'shutil._GiveupOnFastCopy'>\n",
      "  <class 'configparser.Error'>\n",
      "    <class 'configparser.NoSectionError'>\n",
      "    <class 'configparser.DuplicateSectionError'>\n",
      "    <class 'configparser.DuplicateOptionError'>\n",
      "    <class 'configparser.NoOptionError'>\n",
      "    <class 'configparser.InterpolationError'>\n",
      "      <class 'configparser.InterpolationMissingOptionError'>\n",
      "      <class 'configparser.InterpolationSyntaxError'>\n",
      "      <class 'configparser.InterpolationDepthError'>\n",
      "    <class 'configparser.ParsingError'>\n",
      "      <class 'configparser.MissingSectionHeaderError'>\n",
      "  <class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
      "  <class 'zipfile.BadZipFile'>\n",
      "  <class 'zipfile.LargeZipFile'>\n",
      "  <class 'entrypoints.BadEntryPoint'>\n",
      "  <class 'entrypoints.NoSuchEntryPoint'>\n",
      "  <class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
      "  <class 'pydoc.ErrorDuringImport'>\n",
      "  <class 'executing.executing.NotOneValueFound'>\n",
      "  <class 'pure_eval.utils.CannotEval'>\n",
      "  <class 'pygments.util.OptionError'>\n",
      "  <class 'bdb.BdbQuit'>\n",
      "  <class 'pdb.Restart'>\n",
      "  <class 'pexpect.exceptions.ExceptionPexpect'>\n",
      "    <class 'pexpect.exceptions.EOF'>\n",
      "    <class 'pexpect.exceptions.TIMEOUT'>\n",
      "  <class 'ptyprocess.util.PtyProcessError'>\n",
      "  <class 'IPython.utils.process.FindCmdError'>\n",
      "  <class 'IPython.utils.path.HomeDirError'>\n",
      "  <class 'IPython.core.profiledir.ProfileDirError'>\n",
      "  <class 'IPython.core.error.IPythonCoreError'>\n",
      "    <class 'IPython.core.error.TryNext'>\n",
      "    <class 'IPython.core.error.UsageError'>\n",
      "    <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "  <class 'IPython.core.error.InputRejected'>\n",
      "  <class 'getopt.GetoptError'>\n",
      "  <class 'pygments.filters.ErrorToken'>\n",
      "  <class 'IPython.core.prefilter.PrefilterError'>\n",
      "  <class 'IPython.core.alias.AliasError'>\n",
      "    <class 'IPython.core.alias.InvalidAliasError'>\n",
      "  <class 'sqlite3.Error'>\n",
      "    <class 'sqlite3.InterfaceError'>\n",
      "    <class 'sqlite3.DatabaseError'>\n",
      "      <class 'sqlite3.InternalError'>\n",
      "      <class 'sqlite3.OperationalError'>\n",
      "      <class 'sqlite3.ProgrammingError'>\n",
      "      <class 'sqlite3.IntegrityError'>\n",
      "      <class 'sqlite3.DataError'>\n",
      "      <class 'sqlite3.NotSupportedError'>\n",
      "  <class 'sqlite3.Warning'>\n",
      "  <class 'IPython.core.interactiveshell.SpaceInInput'>\n",
      "  <class 'xml.dom.DOMException'>\n",
      "    <class 'xml.dom.IndexSizeErr'>\n",
      "    <class 'xml.dom.DomstringSizeErr'>\n",
      "    <class 'xml.dom.HierarchyRequestErr'>\n",
      "    <class 'xml.dom.WrongDocumentErr'>\n",
      "    <class 'xml.dom.InvalidCharacterErr'>\n",
      "    <class 'xml.dom.NoDataAllowedErr'>\n",
      "    <class 'xml.dom.NoModificationAllowedErr'>\n",
      "    <class 'xml.dom.NotFoundErr'>\n",
      "    <class 'xml.dom.NotSupportedErr'>\n",
      "    <class 'xml.dom.InuseAttributeErr'>\n",
      "    <class 'xml.dom.InvalidStateErr'>\n",
      "    <class 'xml.dom.SyntaxErr'>\n",
      "    <class 'xml.dom.InvalidModificationErr'>\n",
      "    <class 'xml.dom.NamespaceErr'>\n",
      "    <class 'xml.dom.InvalidAccessErr'>\n",
      "    <class 'xml.dom.ValidationErr'>\n",
      "  <class 'prompt_toolkit.validation.ValidationError'>\n",
      "  <class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
      "  <class 'prompt_toolkit.buffer._Retry'>\n",
      "  <class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
      "  <class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
      "  <class 'parso.parser.ParserSyntaxError'>\n",
      "  <class 'parso.parser.InternalParseError'>\n",
      "  <class 'parso.python.diff._PositionUpdatingFinished'>\n",
      "  <class 'jedi.inference.helpers.SimpleGetItemNotFound'>\n",
      "  <class 'jedi.inference.utils.UncaughtAttributeError'>\n",
      "  <class 'jedi.inference.base_value.HasNoContext'>\n",
      "  <class 'jedi.inference.arguments.ParamIssue'>\n",
      "  <class 'jedi.api.exceptions._JediError'>\n",
      "    <class 'jedi.api.exceptions.InternalError'>\n",
      "    <class 'jedi.api.exceptions.WrongVersion'>\n",
      "    <class 'jedi.api.exceptions.RefactoringError'>\n",
      "  <class 'jedi.api.helpers.OnErrorLeaf'>\n",
      "  <class 'jedi.api.environment.InvalidPythonEnvironment'>\n",
      "  <class 'email.errors.MessageError'>\n",
      "    <class 'email.errors.MessageParseError'>\n",
      "      <class 'email.errors.HeaderParseError'>\n",
      "      <class 'email.errors.BoundaryError'>\n",
      "    <class 'email.errors.MultipartConversionError'>\n",
      "    <class 'email.errors.CharsetError'>\n",
      "  <class 'uu.Error'>\n",
      "  <class 'http.client.HTTPException'>\n",
      "    <class 'http.client.NotConnected'>\n",
      "    <class 'http.client.InvalidURL'>\n",
      "    <class 'http.client.UnknownProtocol'>\n",
      "    <class 'http.client.UnknownTransferEncoding'>\n",
      "    <class 'http.client.UnimplementedFileMode'>\n",
      "    <class 'http.client.IncompleteRead'>\n",
      "    <class 'http.client.ImproperConnectionState'>\n",
      "      <class 'http.client.CannotSendRequest'>\n",
      "      <class 'http.client.CannotSendHeader'>\n",
      "      <class 'http.client.ResponseNotReady'>\n",
      "    <class 'http.client.BadStatusLine'>\n",
      "      <class 'http.client.RemoteDisconnected'>\n",
      "    <class 'http.client.LineTooLong'>\n",
      "  <class 'IPython.core.magics.code.InteractivelyDefined'>\n",
      "  <class 'IPython.terminal.embed.KillEmbedded'>\n",
      "  <class 'psutil.Error'>\n",
      "    <class 'psutil.NoSuchProcess'>\n",
      "      <class 'psutil.ZombieProcess'>\n",
      "    <class 'psutil.AccessDenied'>\n",
      "    <class 'psutil.TimeoutExpired'>\n",
      "  <class 'psutil._pslinux._Ipv6UnsupportedError'>\n",
      "  <class 'tornado.queues.QueueEmpty'>\n",
      "  <class 'tornado.queues.QueueFull'>\n",
      "  <class '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'>\n",
      "  <class 'xml.parsers.expat.ExpatError'>\n",
      "  <class 'xmlrpc.client.Error'>\n",
      "    <class 'xmlrpc.client.ProtocolError'>\n",
      "    <class 'xmlrpc.client.ResponseError'>\n",
      "    <class 'xmlrpc.client.Fault'>\n",
      "  <class 'pkg_resources._vendor.pyparsing.exceptions.ParseBaseException'>\n",
      "    <class 'pkg_resources._vendor.pyparsing.exceptions.ParseException'>\n",
      "    <class 'pkg_resources._vendor.pyparsing.exceptions.ParseFatalException'>\n",
      "      <class 'pkg_resources._vendor.pyparsing.exceptions.ParseSyntaxException'>\n",
      "  <class 'pkg_resources._vendor.pyparsing.exceptions.RecursiveGrammarException'>\n",
      "  <class 'pkg_resources.ResolutionError'>\n",
      "    <class 'pkg_resources.VersionConflict'>\n",
      "      <class 'pkg_resources.ContextualVersionConflict'>\n",
      "    <class 'pkg_resources.DistributionNotFound'>\n",
      "    <class 'pkg_resources.UnknownExtra'>\n",
      "  <class '_pydevd_bundle.pydevd_runpy._Error'>\n",
      "  <class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
      "  <class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n"
     ]
    }
   ],
   "source": [
    "# Answere :-\n",
    "# print Python Exception Hierarchy\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + str(exception_class))\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 2)\n",
    "\n",
    "# start from the base class Exception\n",
    "print_exception_hierarchy(Exception)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "79f56ace-c1f1-4977-9281-86f58ead7b0c",
   "metadata": {},
   "source": [
    "This program defines a function called 'print_exception_hierarchy' that takes an exception class and an optional 'indent' parameter. It then prints the name of the exception class, indented by the number of spaces specified by the 'indent' parameter. It then recursively calls itself on all the subclasses of the exception class, passing in the subclass and an increased 'indent' value.The program then starts the recursive process by calling 'print_exception_hierarchy' on the base class 'Exception'. When you run this program, it will output the Python Exception Hierarchy in a tree-like structure, with each exception class indented to show its position in the hierarchy."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ef0808d3-f2d6-4ed0-807e-5d00a9d2b328",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ab311354-87ce-432e-bdb8-e835c5e58ed8",
   "metadata": {},
   "source": [
    "Answere :- The 'ArithmeticError' class is a built-in exception class in Python that is raised when an arithmetic operation fails to execute properly. It is a base class for all errors that occur during arithmetic calculations. Some common errors that are defined in the 'ArithmeticError' class are 'ZeroDivisionError', OverflowError, and 'FloatingPointError'. Here are explanations of two of them with examples:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "48ff45ee-9355-49e5-ac09-5f2a3bba95f5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Caught an exception: division by zero\n"
     ]
    }
   ],
   "source": [
    "# 1. ZeroDivisionError: This error is raised when attempting to divide by zero. For example:\n",
    "# division by zero\n",
    "try:\n",
    "    x = 10/0\n",
    "except ZeroDivisionError as error:\n",
    "    print(f\"Caught an exception: {error}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5b5e9c87-e949-49a9-897b-bea518339d16",
   "metadata": {},
   "source": [
    "2. OverflowError: This error is raised when the result of an arithmetic operation is too large to be represented by the available memory. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9b01aa51-1cff-48d9-83f8-269e232ea6e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# integer overflow\n",
    "import sys\n",
    "try:\n",
    "    x = sys.maxsize + 1\n",
    "except OverflowError as error:\n",
    "    print(f\"Caught an exception:{error}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "175d780a-2a09-4afa-ab9a-25647bb99d21",
   "metadata": {},
   "source": [
    "In the first example, we attempt to divide the number 10 by 0, which is not a valid arithmetic operation, and thus a 'ZeroDivisionError' is raised. In the second example, we attempt to add 1 to the maximum integer value that can be represented by the system, which results in an overflow and a 'OverflowError' is raised.\n",
    "These are just two examples of errors that are defined in the 'ArithmeticError' class. There are several other arithmetic-related errors that can be raised during program execution, depending on the specific scenario in which the error occurs."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6221e7ff-c6d6-4457-b742-6f91dccacd26",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "83c49517-5967-4ea2-a1e5-fd3d8d9f83a3",
   "metadata": {},
   "source": [
    "Answere :- The 'LookupError' class is a built-in exception class in Python that is raised when an index or key used to access an object is invalid. It is the base class for all errors that occur during indexing or key lookup.In general, the 'LookupError' class is used to handle situations where we are trying to access an object using an index or key that does not exist. This can happen with different types of objects like lists, dictionaries, tuples, and so on. Two common subclasses of 'LookupError' are 'KeyError' and 'IndexError'. Here are explanations of these two exceptions with examples:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c4a534cf-8bd1-413b-9a05-a702467fd509",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Caught an exception: 'd'\n"
     ]
    }
   ],
   "source": [
    "#1. 'KeyError': This error is raised when we try to access a dictionary using \n",
    "# a key that does not exist in the #dictionary. For example:\n",
    "\n",
    "# KeyError example\n",
    "my_dict = {\"a\": 1, \"b\": 2, \"c\": 3}\n",
    "try:\n",
    "    x = my_dict[\"d\"]\n",
    "except KeyError as error:\n",
    "    print(f\"Caught an exception: {error}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "20bd4d9e-383c-436e-ae0b-9dc59fb05bf9",
   "metadata": {},
   "source": [
    "In this example, we try to access the value associated with the key \"d\" in the 'my_dict' dictionary, which does not exist. Thus, a 'KeyError' is raised."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ec95dac1-8bdd-4745-a859-8cb6e7b67609",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Caught an exception: list index out of range\n"
     ]
    }
   ],
   "source": [
    "#2. IndexError: This error is raised when we try to access an item in a list or tuple \n",
    "#    using an index that is out of range. For example:\n",
    "\n",
    "# IndexError example\n",
    "my_list = [1, 2, 3]\n",
    "try:\n",
    "    x = my_list[3]\n",
    "except IndexError as error:\n",
    "    print(f\"Caught an exception: {error}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2c591f76-e099-402a-b5d7-fe33b0bcf0e8",
   "metadata": {},
   "source": [
    "In this example, we try to access the item at index 3 in the 'my_list' list, which is out of range since the list only contains three items. Thus, an 'IndexError' is raised.  These are just two examples of errors that are subclasses of the 'LookupError' class. In general, the 'LookupError' class is used to handle situations where we are trying to access an object using an index or key that does not exist."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9ddc1f72-ec72-4715-833e-f8e90a2842a7",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aaf910c9-a9aa-4f07-bd10-c7c0b9516325",
   "metadata": {},
   "source": [
    "Answere :- In Python, modules are reusable pieces of code that can be imported into other Python scripts or modules to add specific functionalities or features. When a Python script tries to import a module and fails to do so, it raises an error called ImportError. ImportError occurs when Python cannot locate a module that a script or module is trying to import. It can occur due to various reasons such as incorrect installation of the module, incorrect path to the module, or the module itself might not exist. For example, if a script tries to import a module called \"numpy\" but the module is not installed in the system, an ImportError will be raised. On the other hand, ModuleNotFoundError is a more specific error that is raised when Python cannot find the module that a script or module is trying to import. It is a subclass of ImportError and was introduced in Python 3.6 to provide more detailed information about the error. ModuleNotFoundError occurs when the specified module does not exist, or the module name is misspelled, or the module is not installed in the system. It can also occur when the module is located in a different directory or when the script is executed in a virtual environment that does not have the module installed. For example, if a script tries to import a module called \"numpy\" but misspells the name as \"nump\", a ModuleNotFoundError will be raised."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "297cff08-bff0-44b7-a01b-6083a6160126",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2993644c-b6b6-489f-99d1-6b231f044674",
   "metadata": {},
   "source": [
    "Answere :- Exception handling is an essential aspect of programming in Python as it allows for the graceful handling of errors and unexpected situations that might occur during program execution. Here are some best practices for exception handling in Python:\n",
    "1. Use specific exception types: It is a good practice to use specific exception types instead of catching general exceptions like the \"Exception\" class. This makes the code more readable and helps to handle specific errors more effectively.\n",
    "2. Use try-except blocks: The try-except block is a widely used construct in Python for handling exceptions. The code inside the try block is executed, and if any exception is raised, the code inside the corresponding except block is executed. It is recommended to use multiple except blocks for handling different types of exceptions.\n",
    "3. Avoid bare except clauses: A bare except clause is a catch-all exception handler that catches all exceptions, including those that were not intended to be caught. This can make it difficult to diagnose and fix errors. Instead, use specific exception handlers that handle only the exceptions that are expected to occur.\n",
    "4. Use finally block: The finally block is executed regardless of whether an exception is raised or not. It is used to perform cleanup actions such as closing files, database connections, or releasing resources.\n",
    "5. Use the \"with\" statement: The \"with\" statement is used to ensure that resources are properly released, even if an exception occurs. It is recommended to use the \"with\" statement for handling file I/O, database connections, and other resources that need to be released after use.\n",
    "6. Log exceptions: Logging exceptions is a good practice as it helps to debug the code and identify the root cause of the error. Python's built-in logging module provides an easy way to log exceptions and other information.\n",
    "7. Raise exceptions: It is a good practice to raise exceptions when an error occurs, rather than ignoring it or returning an error code. This helps to identify the root cause of the error and handle it effectively."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "63578a08-a6f7-474c-b3c9-208ef8387a7b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
